<?php

/* The pro notifications pack */
return [

    'KUPONKODU' => [
            'type' => 'pro',
            'title' => l('notification.kuponkodu.title_default'),
            'description' => l('notification.kuponkodu.description_default'),
            'image' => l('notification.kuponkodu.image_default'),
            'image_alt' => '',
            'coupon_code' => l('notification.kuponkodu.coupon_code_default'),
            'button_url'   => '',
            'url_new_tab' => true,
            'button_text'  => l('notification.kuponkodu.button_text_default'),
            'footer_text'  => l('notification.kuponkodu.footer_text_default'),

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => true,
            'display_branding' => true,

            'title_color' => '#000',
            'description_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'button_background_color' => '#008060',
            'button_color' => '#fff',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
        ],



        'VIDEOBUBBLE' => [
            'type' => 'pro',
            'title' => l('notification.videobubble.title_default'),
            'description' => '',
            'image' => l('notification.videobubble.image_default'),
            'image_alt' => '',
            'coupon_code' => '',
            'button_url'   => l('notification.videobubble.button_url_default'),
            'url_new_tab' => true,
            'button_text'  => l('notification.videobubble.button_text_default'),
            'footer_text'  => '',

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 0,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => -1,
            'display_position' => 'bottom_right',
            'display_close_button' => true,
            'display_branding' => true,

            'title_color' => '#FFF',
            'description_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'button_background_color' => '#008060',
            'button_color' => '#fff',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
        ],
    
    'INFORMATIONAL_BAR' => [
        'type' => 'pro',
        'title' => l('notification.informational_bar.title_default'),
        'description' => l('notification.informational_bar.description_default'),
        'image' => l('notification.informational_bar.image_default'),
        'image_alt' => '',
        'url'   => 'https://eticaret.pro',
        'url_new_tab' => true,

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 0,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => -5,
        'display_position' => 'top',
        'display_close_button' => true,
        'display_branding' => true,

        'title_color' => '#FFF',
        'description_color' => '#FFF',
        'background_color' => '#15002d',
        'background_pattern' => false,
        'background_pattern_svg' => '',

        'border_radius' => 'straight',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow'        => false,

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',
        'close_button_color' => '#FFF',
    ],

    'COUPON' => [
            'type' => 'default',
            'title' => l('notification.coupon.title_default'),
            'description' => l('notification.coupon.description_default'),
            'image' => l('notification.coupon.image_default'),
            'image_alt' => '',
            'coupon_code' => l('notification.coupon.coupon_code_default'),
            'button_url'   => '',
            'url_new_tab' => true,
            'button_text'  => l('notification.coupon.button_text_default'),
            'footer_text'  => l('notification.coupon.footer_text_default'),

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => true,
            'display_branding' => true,

            'title_color' => '#000',
            'description_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'button_background_color' => '#000',
            'button_color' => '#fff',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
        ],


    'IMAGE' => [
        'type' => 'pro',
        'title' => l('notification.image.title_default'),
        'image' => l('notification.image.image_default'),
        'image_alt' => '',
        'button_url'   => 'https://eticaret.pro',
        'button_text'  => l('notification.image.button_text_default'),

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 2,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => 10,
        'display_position' => 'bottom_left',
        'display_close_button' => true,
        'display_branding' => true,

        'title_color' => '#fff',
        'background_color' => '#000',
        'background_pattern' => false,
        'background_pattern_svg' => '',
        'button_background_color' => '#fff',
        'button_color' => '#000',
        'border_radius' => 'rounded',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow'        => true,

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',
        'close_button_color' => '#fff',
    ],

    'COLLECTOR_BAR' => [
        'type' => 'pro',
        'title' => l('notification.collector_bar.title_default'),
        'input_placeholder' => l('notification.collector_bar.input_placeholder_default'),
        'button_text' => l('notification.collector_bar.button_text_default'),
        'show_agreement' => false,
        'agreement_text' => l('notification.collector_bar.agreement_text_default'),
        'agreement_url' => '',
        'thank_you_url' => 'https://eticaret.pro',

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 0,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => -1,
        'display_position' => 'top',
        'display_close_button' => true,
        'display_branding' => true,

        'title_color' => '#000',
        'background_color' => '#EDE9FF',
        'background_pattern' => false,
        'background_pattern_svg' => '',
        'button_background_color' => '#795EF1',
        'button_color' => '#fff',
        'border_radius' => 'straight',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow'        => false,

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',
        'close_button_color' => '#808080',

        'data_send_is_enabled' => 0,
        'data_send_webhook' => '',
        'data_send_email' => '',
    ],

    'COUPON_BAR' => [
        'type' => 'pro',
        'title' => l('notification.coupon_bar.title_default'),
        'coupon_code' => l('notification.coupon_bar.coupon_code_default'),
        'url'   => 'https://eticaret.pro',
        'url_new_tab' => true,

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 0,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => -1,
        'display_position' => 'top',
        'display_close_button' => true,
        'display_branding' => true,

        'title_color' => '#fff',
        'coupon_code_color' => '#000',
        'coupon_code_background_color' => '#fff',
        'coupon_code_border_color' => '#fff',
        'background_color' => '#000',
        'background_pattern' => false,
        'background_pattern_svg' => '',

        'border_radius' => 'straight',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow'        => false,
        'close_button_color' => '#808080',

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',
    ],

    'MARQUEE_BAR' => [
        'type' => 'pro',
        'title' => l('notification.marquee_bar.title_default'),
        'coupon_code' => l('notification.marquee_bar.coupon_code_default'),
        'url'   => 'https://eticaret.pro',
        'url_new_tab' => true,

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 0,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => -1,
        'display_position' => 'top',
        'display_close_button' => true,
        'display_branding' => true,

        'title_color' => '#fff',
        'coupon_code_color' => '#eb3e3d',
        'background_color' => '#eb3e3d',
        'background_pattern' => false,
        'background_pattern_svg' => '',

        'border_radius' => 'straight',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow'        => false,
        'close_button_color' => '#808080',

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',
    ],

    'BUTTON_BAR' => [
        'type' => 'pro',
        'title' => l('notification.button_bar.title_default'),
        'button_text' => l('notification.button_bar.button_text_default'),
        'url'   => 'https://eticaret.pro',
        'url_new_tab' => true,

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 2,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => 10,
        'display_position' => 'top',
        'display_close_button' => true,
        'display_branding' => true,

        'title_color' => '#fff',
        'button_color' => '#000',
        'button_background_color' => '#fff',
        'background_color' => '#000',
        'background_pattern' => false,
        'background_pattern_svg' => '',

        'border_radius' => 'straight',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow'        => false,
        'close_button_color' => '#808080',

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',
    ],

    'COLLECTOR_MODAL' => [
        'type' => 'pro',
        'title' => l('notification.collector_modal.title_default'),
        'description' => l('notification.collector_modal.description_default'),
        'image' => l('notification.collector_modal.image_default'),
        'image_alt' => '',
        'input_placeholder' => l('notification.collector_modal.input_placeholder_default'),
        'button_text' => l('notification.collector_modal.button_text_default'),
        'show_agreement' => false,
        'agreement_text' => l('notification.collector_modal.agreement_text_default'),
        'agreement_url' => '',
        'thank_you_url' => '',

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 2,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => 10,
        'display_position' => 'bottom_left',
        'display_close_button' => true,
        'display_branding' => true,

        'title_color' => '#000',
        'description_color' => '#000',
        'background_color' => '#fff',
        'background_pattern' => false,
        'background_pattern_svg' => '',
        'button_background_color' => '#272727',
        'button_color' => '#fff',
        'border_radius' => 'rounded',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow'        => true,
        'close_button_color' => '#808080',

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',

        'data_send_is_enabled' => 0,
        'data_send_webhook' => '',
        'data_send_email' => '',
    ],

    'COLLECTOR_TWO_MODAL' => [
        'type' => 'pro',
        'title' => l('notification.collector_two_modal.title_default'),
        'description' => l('notification.collector_two_modal.description_default'),
        'image' => l('notification.collector_two_modal.image_default'),
        'image_alt' => '',
        'input_placeholder' => l('notification.collector_two_modal.input_placeholder_default'),
        'button_text' => l('notification.collector_two_modal.button_text_default'),
        'show_agreement' => false,
        'agreement_text' => l('notification.collector_two_modal.agreement_text_default'),
        'agreement_url' => '',
        'thank_you_url' => '',

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 2,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => 10,
        'display_position' => 'bottom_left',
        'display_close_button' => true,
        'display_branding' => true,

        'title_color' => '#004e00',
        'description_color' => '#000',
        'background_color' => '#fff',
        'background_pattern' => false,
        'background_pattern_svg' => '',
        'button_background_color' => '#004e00',
        'button_color' => '#fff',
        'border_radius' => 'rounded',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow'        => true,
        'close_button_color' => '#808080',

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',

        'data_send_is_enabled' => 0,
        'data_send_webhook' => '',
        'data_send_email' => '',
    ],


     'VIDEO' => [
            'type' => 'default',
            'title' => l('notification.video.title_default'),
            'video' => '',
            'button_url'   => '',
            'button_text'  => l('notification.video.button_text_default'),
            'url_new_tab' => '',

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => true,
            'display_branding' => true,

            'title_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'button_background_color' => '#000',
            'button_color' => '#fff',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
        ],

    'BUTTON_MODAL' => [
        'type' => 'pro',
        'title' => l('notification.button_modal.title_default'),
        'description' => l('notification.button_modal.description_default'),
        'image' => l('notification.button_modal.image_default'),
        'image_alt' => '',
        'button_text' => l('notification.button_modal.button_text_default'),
        'button_url'   => 'https://eticaret.pro',

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 2,
        'display_frequency' => 'once_per_session',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => 15,
        'display_position' => 'middle_right',
        'display_close_button' => true,
        'display_branding' => true,

        'title_color' => '#000',
        'description_color' => '#000',
        'background_color' => '#F5F9BE',
        'background_pattern' => false,
        'background_pattern_svg' => '',
        'button_background_color' => '#272727',
        'button_color' => '#fff',
        'border_radius' => 'rounded',
        'border_color' => '#000',
        'border_width' => 3,
        'shadow'        => true,
        'close_button_color' => '#000',

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',
    ],

    'TEXT_FEEDBACK' => [
        'type' => 'pro',
        'title' => l('notification.text_feedback.title_default'),
        'description' => l('notification.text_feedback.description_default'),
        'input_placeholder' => l('notification.text_feedback.input_placeholder_default'),
        'button_text' => l('notification.text_feedback.button_text_default'),
        'thank_you_url' => 'https://eticaret.pro',

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 2,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => 10,
        'display_position' => 'bottom_left',
        'display_close_button' => true,
        'display_branding' => true,

        'title_color' => '#004c48',
        'description_color' => '#000',
        'background_color' => '#e9fff5',
        'background_pattern' => false,
        'background_pattern_svg' => '',
        'button_background_color' => '#004c48',
        'button_color' => '#fff',
        'border_radius' => 'rounded',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow'        => true,
        'close_button_color' => '#808080',

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',

        'data_send_is_enabled' => 0,
        'data_send_webhook' => '',
        'data_send_email' => '',
    ],

    'ENGAGEMENT_LINKS' => [
        'type' => 'pro',
        'title' => l('notification.engagement_links.title'),
        'categories' => [],

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 2,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => 10,
        'display_position' => 'bottom_left',
        'display_close_button' => true,
        'display_branding' => true,

        'title_color' => '#EDEFFF',
        'categories_title_color' => '#c0c5f7',
        'categories_description_color' => '#c0c5f7',
        'categories_links_title_color' => '#c0c5f7',
        'categories_links_description_color' => '#c0c5f7',
        'categories_links_background_color' => '#e2e2e2',
        'categories_links_border_color' => '#fff',
        'background_color' => '#3542b1',
        'background_pattern' => false,
        'background_pattern_svg' => '',
        'button_background_color' => '#272727',
        'button_color' => '#fff',
        'border_radius' => 'rounded',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow'        => true,
        'close_button_color' => '#808080',

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',
    ],

    'WHATSAPP_CHAT' => [
        'type' => 'pro',
        'title' => l('notification.whatsapp_chat.title_default'),
        'agent_image' => l('notification.whatsapp_chat.image_default'),
        'agent_image_alt' => '',
        'agent_name' => l('notification.whatsapp_chat.agent_name_default'),
        'agent_description' => l('notification.whatsapp_chat.agent_description_default'),
        'agent_message' => l('notification.whatsapp_chat.agent_message_default'),
        'agent_phone_number' => l('notification.whatsapp_chat.agent_phone_number_default'),
        'button_text' => l('notification.whatsapp_chat.button_text_default'),

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 0,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => -1,
        'display_position' => 'bottom_left',
        'display_close_button' => true,
        'display_branding' => true,

        'header_agent_name_color' => '#fff',
        'header_agent_description_color' => '#d5fff6',
        'header_background_color' => '#085E54',
        'content_background_color' => '#eaeaea',
        'content_agent_name_color' => '#2d3748',
        'content_agent_message_color' => '#2d3748',
        'content_agent_message_background_color' => '#fff',
        'footer_background_color' => '#fff',
        'footer_button_background_color' => '#14c656',
        'footer_button_color' => '#fff',

        'title_color' => '#000',
        'background_color' => '#fff',
        'background_pattern' => false,
        'background_pattern_svg' => '',
        'button_background_color' => '#272727',
        'button_color' => '#fff',
        'border_radius' => 'rounded',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow' => true,
        'close_button_color' => '#808080',

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',
    ],

    'FACEBOOK_CHAT' => [
        'type' => 'pro',
        'title' => l('notification.facebook_chat.title_default'),
        'agent_image' => l('notification.facebook_chat.image_default'),
        'agent_image_alt' => '',
        'agent_name' => l('notification.facebook_chat.agent_name_default'),
        'agent_description' => l('notification.facebook_chat.agent_description_default'),
        'agent_message' => l('notification.facebook_chat.agent_message_default'),
        'agent_phone_number' => l('notification.facebook_chat.agent_phone_number_default'),
        'button_text' => l('notification.facebook_chat.button_text_default'),

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 0,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => -1,
        'display_position' => 'bottom_left',
        'display_close_button' => true,
        'display_branding' => true,

        'header_agent_name_color' => '#1d2129',
        'header_agent_description_color' => '#1d2129',
        'header_background_color' => '#FAFAFA',
        'content_background_color' => '#FFF',
        'content_agent_name_color' => '#2d3748',
        'content_agent_message_color' => '#2d3748',
        'content_agent_message_background_color' => '#f1f0f0',
        'footer_background_color' => '#fff',
        'footer_button_background_color' => '#0084FF',
        'footer_button_color' => '#fff',

        'title_color' => '#000',
        'background_color' => '#fff',
        'background_pattern' => false,
        'background_pattern_svg' => '',
        'button_background_color' => '#272727',
        'button_color' => '#fff',
        'border_radius' => 'rounded',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow' => true,
        'close_button_color' => '#808080',

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'font' => 'inherit',
    ],


    'CONTACT_US' => [
        'type' => 'pro',
        'title' => l('notification.contact_us.title_default'),
        'description' => l('notification.contact_us.description_default'),
        'contact_email' => l('notification.contact_us.contact_email_default'),
        'contact_phone_number' => l('notification.contact_us.contact_phone_number_default'),
        'contact_whatsapp' => l('notification.contact_us.contact_whatsapp_default'),
        'contact_telegram' => l('notification.contact_us.contact_telegram_default'),
        'contact_facebook_messenger' => l('notification.contact_us.contact_facebook_messenger_default'),

        'trigger_all_pages' => true,
        'triggers' => [],
        'display_trigger' => 'delay',
        'display_trigger_value' => 2,
        'display_frequency' => 'all_time',
        'display_mobile' => true,
        'display_desktop' => true,

        'direction' => l('direction'),
        'display_duration' => 10,
        'display_position' => 'bottom_left',
        'display_close_button' => true,
        'display_branding' => true,

        'title_color' => '#000',
        'description_color' => '#000',
        'background_color' => '#fff',
        'background_pattern' => false,
        'background_pattern_svg' => '',
        'border_radius' => 'rounded',
        'border_color' => '#000',
        'border_width' => 0,
        'shadow'        => true,

        'on_animation' => 'fadeIn',
        'off_animation' => 'fadeOut',
        'animation' => '',
        'animation_interval' => '3',
        'font' => 'inherit',
        'close_button_color' => '#808080',
    ],


    'SNOW' => [
            'type' => 'pro',
            'title' => l('notification.snow.html_default'),
            'html' => l('notification.snow.html_default'),

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 0,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => -1,
            'display_position' => 'bottom_left',
            'display_close_button' => true,
            'display_branding' => true,

            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',

            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
    ],

            'BROWSERALERT' => [
            'type' => 'pro',
            'title' => l('notification.browseralert.html_default'),
            'html' => l('notification.browseralert.html_default'),

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 0,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => -1,
            'display_position' => 'bottom_left',
            'display_close_button' => true,
            'display_branding' => true,

            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',

            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
    ],
    

 'INFORMATIONAL' => [
            'type' => 'default',
            'title' => l('notification.informational.title_default'),
            'description' => l('notification.informational.description_default'),
            'image' => l('notification.informational.image_default'),
            'image_alt' => '',
            'url'   => '',
            'url_new_tab' => true,

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => true,
            'display_branding' => true,

            'title_color' => '#000',
            'description_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',

            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
        ],

        
        'LIVE_COUNTER' => [
            'type' => 'default',
            'description' => l('notification.live_counter.description_default'),
            'last_activity' => 15,
            'url'   => '',
            'url_new_tab' => true,

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',

            'direction' => l('direction'),
            'display_trigger_value' => 2,
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_minimum_activity' => 0,
            'display_frequency' => 'all_time',
            'display_close_button' => true,
            'display_branding' => true,
            'display_mobile' => true,
            'display_desktop' => true,

            'number_color' => '#fff',
            'number_background_color' => '#000',
            'description_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
            'pulse_background_color' => '#17bf21',
        ],

        'EMAIL_COLLECTOR' => [
            'type' => 'default',
            'title' => l('notification.email_collector.title_default'),
            'description' => l('notification.email_collector.description_default'),
            'name_placeholder' => l('notification.email_collector.name_placeholder_default'),
            'email_placeholder' => l('notification.email_collector.email_placeholder_default'),
            'button_text' => l('notification.email_collector.button_text_default'),
            'show_agreement' => false,
            'agreement_text' => l('notification.email_collector.agreement_text_default'),
            'agreement_url' => '',
            'thank_you_url' => '',

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => true,
            'display_branding' => true,

            'title_color' => '#000',
            'description_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'button_background_color' => '#272727',
            'button_color' => '#fff',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',

            'data_send_is_enabled' => 0,
            'data_send_webhook' => '',
            'data_send_email' => '',
        ],

        'CONVERSIONS' => [
            'type' => 'default',
            'title' => l('notification.conversions.title_default'),
            'description' => l('notification.conversions.description_default'),
            'image' => l('notification.conversions.image_default'),
            'image_alt' => '',
            'url'   => '',
            'url_new_tab' => true,
            'conversions_count' => 1,
            'in_between_delay' => 3,
            'order' => 'descending',

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,


            'direction' => l('direction'),
            'display_minimum_activity' => 0,
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => true,
            'display_branding' => true,

            'title_color' => '#000',
            'date_color' => '#808080',
            'description_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',

            'data_trigger_auto' => false,
            'data_triggers_auto' => []
        ],

        'CONVERSIONS_COUNTER' => [
            'type' => 'default',
            'title' => l('notification.conversions_counter.title_default'),
            'last_activity' => 2,
            'url' => '',
            'url_new_tab' => true,

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',

            'direction' => l('direction'),
            'display_trigger_value' => 2,
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_minimum_activity' => 0,
            'display_frequency' => 'all_time',
            'display_close_button' => false,
            'display_branding' => true,
            'display_mobile' => true,
            'display_desktop' => true,

            'number_color' => '#fff',
            'number_background_color' => '#000',
            'title_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',

            'data_trigger_auto' => false,
            'data_triggers_auto' => []
        ],

       

        'SOCIAL_SHARE' => [
            'type' => 'default',
            'title' => l('notification.social_share.title_default'),
            'description' => l('notification.social_share.description_default'),
            'share_url'   => '',
            'share_facebook' => true,
            'share_twitter' => true,
            'share_linkedin' => true,
            'share_pinterest' => true,
            'share_reddit' => true,

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => true,
            'display_branding' => true,

            'title_color' => '#000',
            'description_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
        ],

        'REVIEWS' => [
            'type' => 'default',
            'url'   => '',
            'url_new_tab' => true,
            'reviews_count' => 1,
            'title' => l('notification.reviews.title_default'),
            'description' => l('notification.reviews.description_default'),
            'image' => l('notification.reviews.image_default'),
            'image_alt' => '',
            'stars' => 5,
            'in_between_delay' => 3,
            'order' => 'random',

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => false,
            'display_branding' => true,

            'title_color' => '#000',
            'description_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
        ],

        'EMOJI_FEEDBACK' => [
            'type' => 'default',
            'title' => l('notification.emoji_feedback.title_default'),
            'show_angry' => true,
            'show_sad' => true,
            'show_neutral' => true,
            'show_happy' => true,
            'show_excited' => true,
            'thank_you_url' => '',

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => false,
            'display_branding' => true,

            'title_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
        ],

        'COOKIE_NOTIFICATION' => [
            'type' => 'default',
            'description' => l('notification.cookie_notification.description_default'),
            'image' => l('notification.cookie_notification.image_default'),
            'image_alt' => '',
            'url_text' => l('notification.cookie_notification.url_text_default'),
            'url' => '',
            'url_new_tab' => true,
            'button_text'  => l('notification.cookie_notification.button_text_default'),

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => true,
            'display_branding' => true,

            'description_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'button_background_color' => '#000',
            'button_color' => '#fff',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
        ],

        'SCORE_FEEDBACK' => [
            'type' => 'default',
            'title' => l('notification.score_feedback.title_default'),
            'description' => l('notification.score_feedback.description_default'),
            'thank_you_url' => '',

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => false,
            'display_branding' => true,

            'title_color' => '#000',
            'description_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'button_background_color' => '#000',
            'button_color' => '#fff',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
        ],

        'REQUEST_COLLECTOR' => [
            'type' => 'default',
            'title' => l('notification.request_collector.title_default'),
            'description' => l('notification.request_collector.description_default'),
            'image' => l('notification.request_collector.image_default'),
            'image_alt' => '',
            'content_title' => l('notification.request_collector.content_title_default'),
            'content_description' => l('notification.request_collector.content_description_default'),
            'input_placeholder' => l('notification.request_collector.input_placeholder_default'),
            'button_text' => l('notification.request_collector.button_text_default'),
            'show_agreement' => false,
            'agreement_text' => l('notification.request_collector.agreement_text_default'),
            'agreement_url' => '',
            'thank_you_url' => '',

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => false,
            'display_branding' => true,

            'title_color' => '#000',
            'description_color' => '#000',
            'content_title_color' => '#000',
            'content_description_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'button_background_color' => '#000',
            'button_color' => '#fff',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',

            'data_send_is_enabled' => 0,
            'data_send_webhook' => '',
            'data_send_email' => '',
        ],

        'COUNTDOWN_COLLECTOR' => [
            'type' => 'default',
            'title' => l('notification.countdown_collector.title_default'),
            'description' => l('notification.countdown_collector.description_default'),
            'content_title' => l('notification.countdown_collector.content_title_default'),
            'input_placeholder' => l('notification.countdown_collector.input_placeholder_default'),
            'button_text' => l('notification.countdown_collector.button_text_default'),
            'end_date' => (new \DateTime())->modify('+5 hours')->format('Y-m-d H:i:s'),
            'show_agreement' => false,
            'agreement_text' => l('notification.countdown_collector.agreement_text_default'),
            'agreement_url' => '',
            'thank_you_url' => '',

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => 10,
            'display_position' => 'bottom_left',
            'display_close_button' => false,
            'display_branding' => true,

            'title_color' => '#000',
            'description_color' => '#000',
            'content_title_color' => '#000',
            'time_color' => '#fff',
            'time_background_color' => '#000',
            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',
            'button_background_color' => '#000',
            'button_color' => '#fff',
            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',

            'data_send_is_enabled' => 0,
            'data_send_webhook' => '',
            'data_send_email' => '',
        ],

        'CUSTOM_HTML' => [
            'type' => 'default',
            'html' => l('notification.custom_html.html_default'),
            'css' => l('notification.custom_html.css_default'),
            'js' => l('notification.custom_html.js_default'),

            'trigger_all_pages' => true,
            'triggers' => [],
            'display_trigger' => 'delay',
            'display_trigger_value' => 2,
            'display_frequency' => 'all_time',
            'display_mobile' => true,
            'display_desktop' => true,

            'direction' => l('direction'),
            'display_duration' => -1,
            'display_position' => 'top_floating',
            'display_close_button' => true,
            'display_branding' => true,

            'background_color' => '#fff',
            'background_pattern' => false,
            'background_pattern_svg' => '',

            'border_radius' => 'rounded',
            'border_color' => '#000',
            'border_width' => 0,
            'shadow'        => true,

            'on_animation' => 'fadeIn',
            'off_animation' => 'fadeOut',
            'animation' => '',
            'animation_interval' => '3',
            'font' => 'inherit',
            'close_button_color' => '#808080',
        ],

     

    

];
